## CI

image: edbizarro/gitlab-ci-pipeline-php:7.4-alpine

# stages
stages:
  - build
  - verify

## jobs:

# release job base
.release:
  only:
    refs:
      - master

# ssh job base
.ssh:
  extends: .release
  before_script:
    ##
    ## Install ssh-agent if not already installed, it is required by Docker.
    ## (change apt-get to yum if you use an RPM-based image)
    ##
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'

    ##
    ## Run ssh-agent (inside the build environment)
    ##
    - eval $(ssh-agent -s)

    ##
    ## Add the SSH key stored in SSH_PRIVATE_KEY variable to the agent store
    ## We're using tr to fix line endings which makes ed25519 keys work
    ## without extra base64 encoding.
    ## https://gitlab.com/gitlab-examples/ssh-private-key/issues/1#note_48526556
    ##
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null

    ##
    ## Create the SSH directory and give it the right permissions
    ##
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh

    ##
    ## Optionally, if you will be using any Git commands, set the user name and
    ## and email.
    ##
    #- git config --global user.email "user@example.com"
    #- git config --global user.name "User name"

# build jobs

composer:
  extends: .release
  stage: build
  script:
    - composer install --no-ansi --no-interaction --no-progress --no-scripts --prefer-dist
    - mv build.env .env || cp .env.example .env
    - php artisan key:generate
  artifacts:
    expire_in: 1 month
    paths:
      - vendor/
      - .env
  cache:
    key: ${CI_COMMIT_REF_SLUG}-composer
    paths:
      - vendor/


# test jobs

test:
  extends: .release
  stage: verify
  # List of jobs from which it will download the artifacts.
  dependencies:
    - composer
    - npm
  script:
    - vendor/bin/phpunit -v --coverage-text --colors=never --stderr
#  artifacts:
#    paths:
#      - ./storage/logs # for debugging
#    expire_in: 7 days
#    when: always

#codestyle:
#  extends: .release
#  stage: verify
#  image: lorisleiva/laravel-docker
#  dependencies: []
#  script:
#    - phpcs --standard=PSR2 --extensions=php app


