name: PHP

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        laravel-version: ['^6.0', 'master']
        stabilty: ['stable', 'lowest']
        php-versions: ['7.4']
    name: PHP ${{ matrix.php-versions }}  on ${{ matrix.laravel-version }} (${{ matrix.stabilty }})
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extension-csv: mbstring, xdebug
          coverage: xdebug
      - name: Install dependencies
        run: |
          composer require --no-update --no-interaction "illuminate/support:${{ matrix.laravel-version }}"
          composer update --prefer-${{ matrix.stabilty }} --no-interaction --prefer-dist --no-suggest
      - name: Lint composer.json
        run: composer validate
      - name: Run Tests
        run: composer test:ci
      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage.xml #optional
          flags: unittests #optional
          name: codecov-umbrella #optional
          yml: ./codecov.yml #optional
          fail_ci_if_error: true #optional (default = false)
